# Generated by Django 4.2.9 on 2025-02-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('first_horse', models.CharField(max_length=255)),
                ('first_jockey', models.CharField(max_length=255)),
                ('first_trainer', models.CharField(max_length=255)),
                ('second_horse', models.CharField(max_length=255)),
                ('second_jockey', models.CharField(max_length=255)),
                ('second_trainer', models.CharField(max_length=255)),
                ('third_horse', models.CharField(max_length=255)),
                ('third_jockey', models.CharField(max_length=255)),
                ('third_trainer', models.CharField(max_length=255)),
                ('race_number', models.PositiveIntegerField(blank=True, null=True)),
                ('race_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'winners2',
            },
        ),
    ]
